development:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: surveyor
  pool:     5
  template: template0

production:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: surveyor
  pool:     5
  template: template0
